services:
  foresight-api-gateway:
    build:
      context: ../foresight-api-gateway
      dockerfile: Dockerfile.dev
    container_name: foresight-api-gateway-c
    ports:
      - 4000:4000
    env_file:
      - ../foresight-api-gateway/.env
    volumes:
      - ../foresight-api-gateway:/app
      - api_gateway_node_modules:/app/node_modules
    depends_on:
      - foresight-gitlab-service
  
  foresight-gitlab-service:
    build:
      context: ../foresight-gitlab-service
      dockerfile: Dockerfile.dev
    container_name: foresight-gitlab-service-c
    ports:
      - 4001:4001
    env_file:
      - ../foresight-gitlab-service/.env
    volumes:
      - ../foresight-gitlab-service:/app
      - gitlab_service_node_modules:/app/node_modules

volumes:
  api_gateway_node_modules:
  gitlab_service_node_modules: